name: "Install uv"
description: "Install uv use mcommunity action"
runs:
  using: composite
  steps:
    - name: "Install UV"
      shell: bash
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
